# Generated by Django 4.2.7 on 2023-11-30 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_user_alter_message_id_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='chatrooms', to='chat.user'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='max_members',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
